export const perfumeSchema = {
  name: 'perfume',
  title: 'Perfume',
  type: 'document',
  fields: [
    { name: 'name', type: 'string', title: 'Nombre' },
    { name: 'slug', type: 'slug', title: 'Slug', options: { source: 'name' } },
    { name: 'brand', type: 'string', title: 'Marca', options: { list: ['Lattafa', 'Armaf', 'Afnan', 'Maison Alhambra', 'Rasasi'] } },
    { name: 'description', type: 'text', title: 'Descripción', rows: 3 },
    { name: 'price', type: 'string', title: 'Precio (ej: $74.000)' },
    { name: 'priceOriginal', type: 'string', title: 'Precio original (opcional)' },
    { name: 'image', type: 'image', title: 'Imagen', options: { hotspot: true } },
    { name: 'imageUrl', type: 'string', title: 'URL de imagen (alternativa)' },
    { name: 'badge', type: 'string', title: 'Badge', options: { list: [{ title: 'Ninguno', value: '' }, 'Más vendido', 'Nuevo', 'Top', 'Exclusivo'] } },
    { name: 'category', type: 'string', title: 'Categoría', options: { list: ['hombre', 'mujer', 'unisex'] } },
    { name: 'family', type: 'string', title: 'Familia', options: { list: ['dulces', 'frescos', 'orientales', 'maderosos', 'florales'] } },
    { name: 'duration', type: 'string', title: 'Duración (ej: 8-10 hs)' },
    { name: 'ml', type: 'number', title: 'ML' },
    { name: 'inspiredBy', type: 'string', title: 'Inspirado en (opcional)' },
    { name: 'outOfStock', type: 'boolean', title: 'Agotado', initialValue: false },
    { name: 'offerDiscount', type: 'number', title: 'Descuento Hot Sale (%)' },
    { name: 'offerEndsAt', type: 'string', title: 'Oferta válida hasta (ej: 2026-05-20T23:59:00)' },
    { name: 'order', type: 'number', title: 'Orden en catálogo' },
  ],
  orderings: [{ title: 'Orden', name: 'orderAsc', by: [{ field: 'order', direction: 'asc' }] }],
  preview: {
    select: { title: 'name', subtitle: 'brand', media: 'image' },
  },
}
