export const perfumeSchema = {
  name: 'perfume',
  title: 'Perfume',
  type: 'document',
  fields: [
    { name: 'name', type: 'string', title: 'Nombre' },
    { name: 'slug', type: 'slug', title: 'Slug', options: { source: 'name' } },
    { name: 'brand', type: 'string', title: 'Marca', options: { list: ['Lattafa', 'Armaf', 'Afnan', 'Maison Alhambra', 'Rasasi', 'Al Wataniah', 'French Avenue'] } },
    { name: 'description', type: 'text', title: 'Descripción', rows: 3 },
    { name: 'price', type: 'string', title: 'Precio (ej: $74.000)' },
    { name: 'priceOriginal', type: 'string', title: 'Precio original (opcional)' },
    { name: 'image', type: 'image', title: 'Imagen (frasco completo)', options: { hotspot: true } },
    { name: 'imageUrl', type: 'string', title: 'URL de imagen (alternativa)' },
    { name: 'imageDecant', type: 'image', title: 'Imagen decant', options: { hotspot: true } },
    { name: 'imageDecantUrl', type: 'string', title: 'URL imagen decant (alternativa)' },
    { name: 'badge', type: 'string', title: 'Badge', options: { list: [{ title: 'Ninguno', value: '' }, 'Más vendido', 'Nuevo', 'Top', 'Exclusivo'] } },
    { name: 'category', type: 'string', title: 'Categoría', options: { list: ['hombre', 'mujer', 'unisex'] } },
    { name: 'family', type: 'string', title: 'Familia', options: { list: ['dulces', 'frescos', 'orientales', 'maderosos', 'florales', 'aromaticas', 'aromaticas acuaticas'] } },
    { name: 'duration', type: 'string', title: 'Duración (ej: 8-10 hs)' },
    { name: 'ml', type: 'number', title: 'ML (frasco completo)' },
    {
      name: 'variants',
      type: 'array',
      title: 'Variantes de ML (decants)',
      description: 'Agregá los tamaños extra con su precio. Ej: 5ml, 10ml, 15ml.',
      of: [{
        type: 'object',
        title: 'Variante',
        fields: [
          { name: 'ml', type: 'number', title: 'ML' },
          { name: 'price', type: 'string', title: 'Precio (ej: $8.000)' },
        ],
        preview: { select: { title: 'ml', subtitle: 'price' } },
      }],
    },
    { name: 'inspiredBy', type: 'string', title: 'Inspirado en (opcional)' },
    { name: 'outOfStock', type: 'boolean', title: 'Agotado', initialValue: false },
    { name: 'isDecant', type: 'boolean', title: 'Es Decant', initialValue: false },
    { name: 'offerDiscount', type: 'number', title: 'Descuento Hot Sale (%)' },
    { name: 'offerEndsAt', type: 'string', title: 'Oferta válida hasta (ej: 2026-05-20T23:59:00)' },
    { name: 'order', type: 'number', title: 'Orden en catálogo' },
  ],
  orderings: [{ title: 'Orden', name: 'orderAsc', by: [{ field: 'order', direction: 'asc' }] }],
  preview: {
    select: { title: 'name', subtitle: 'brand', media: 'image' },
  },
}
